version: '3.8'

x-environment-defaults: &environment-defaults
  DEBUG: "True"
  DB_NAME: "horns_and_hooves"
  DB_USER: "postgres"
  DB_PASSWORD: "izelah69"
  DB_HOST: "postgres-db"
  DB_PORT: 5432
  SECRET_KEY: 'django-insecure-p%p=l+s!q4^+3hzv$rc9)6a=$b_i^tog*64+j*lxy7ieu4(alz'

services:
  app:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn config.wsgi:application -c gunicorn.conf.py"
    ports:
      - "8001:8000"
    depends_on:
      - postgres-db
    environment:
      <<: *environment-defaults
      STATIC_ROOT: /app/static
    volumes:
      - static_volume:/app/static/
    restart: always

  postgres-db:
    image: postgres:latest
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5433:5432"
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d ${DB_NAME} -U ${DB_USER}' ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static/
    depends_on:
      - app

volumes:
  static_volume: